source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.3'
inhibit_all_warnings!
use_frameworks!

target 'SB-Maps' do
  pod 'SnapKit', '~> 4.0.0' # autolayout
  pod 'XCGLogger', :git => 'https://github.com/GetJOMO/XCGLogger.git', :branch => 'feature/jomo_xcode_colors' # logging
  pod 'SwiftLocation', '~> 2.0.7' # core location manager
end

target 'SB-MapsTests' do

end

